### DISCUSSION TITLE
Docker Container Security

### DISCUSSION THREAD

**Discussion by stonkage** [jordan-dalby/ByteStash#123] [Ideas]
Love the project great work!!

I have been able to futher lock down the container (without lost of functionality) using the following and also added a health check

```
    user: PUID:GUID
    security_opt:
      - no-new-privileges:true
    read_only: true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - --timeout=10
        - http://IP:port/
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
```
