### DISCUSSION TITLE
n00b here: How can I backup the code snippets? Or backup the snippetsto restore?

### DISCUSSION THREAD

**Discussion by kmanan** [jordan-dalby/ByteStash#139] [Q&A]
Hi, still learning Docker, lvoe the idea of this project but how do I make sure I don't lose the code snippets?

**Comment by jordan-dalby** [comment]
@kmanan 
Hi!
If you're using docker-compose to setup the project:
```
services:
  bytestash:
    image: "ghcr.io/jordan-dalby/bytestash:latest"
    restart: always
    volumes:
      - /your/snippet/path:/data/snippets
    ports:
      - "5000:5000"
    environment:
      # See https://github.com/jordan-dalby/ByteStash/wiki/FAQ#environment-variables
      JWT_SECRET: your-secret
      TOKEN_EXPIRY: 24h
      ALLOW_NEW_ACCOUNTS: "true"
```
Under the `volumes` section, change `/your/snippet/path` to an actual location on your system, e.g. 
```
  volumes:
    - "C:/Users/myuser/bytestash/snippets:/data/snippets"
```
Make sure to only edit the left-hand side.
Then `docker-compose -f mydockerfile.yaml up` to start the container.

You can find your database in `C:/Users/myuser/bytestash/snippets` (given my example above), copy all files in there to make a full backup.
