### ISSUE TITLE
Allow ByteStash to work under subpath

### ISSUE THREAD

**Issue by Trungtin1011** [jordan-dalby/ByteStash#21]
Hi, I currently figured out that ByteStash cannot be hosted under subpath for Ingress deployment on Kubernetes. 

Can you by somehow add the feature so that ByteStash can be hosted under subpath (/bytestash)?

**Comment by jordan-dalby** [comment]
@Trungtin1011 
I just released a dev version, can you test it?
ghcr.io/jordan-dalby/bytestash-dev:pr-23

Use BASE_PATH environment variable to set the desired path.

**Comment by Trungtin1011** [comment]
Hi @jordan-dalby,

Thank you for your quick response. I've just tried with the new image and here are the results:
1. API endpoint `/api/snippets` works fine with `BASE_PATH` environment variable setting
2. I used Kubernetes Ingress with `pathType = Prefix` for Bytestash, but it seemed to be unable to load assets files for the UI such as `assets/index-DhTxxoCL.js` and `assets/index-hGZFs1YF.css`. The server cannot append the subpath to load those files (below image). I've also tried with Ingress re-write but not worked.

<img width="843" alt="Screenshot 2024-11-03 at 10 25 21" src="https://github.com/user-attachments/assets/1e58d314-db8c-4bbe-b65f-9c8fbc3ed153">


I very appreciate that you are listening to our requests and hope this can be done in the next release.

**Comment by jordan-dalby** [comment]
@Trungtin1011 
Can you send your Kubernetes Ingress file so I can take a look? It could be a configuration issue.

**Comment by Trungtin1011** [comment]
@jordan-dalby,

Here is my Ingress manifest:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: bytestash
  name: bytestash
spec:
  ingressClassName: nginx
  rules:
    - host: my-domain.com
      http:
        paths:
          - backend:
              service:
                name: bytestash
                port:
                  number: 5000
            path: /bytestash
            pathType: Prefix
```

**Comment by jordan-dalby** [comment]
@Trungtin1011 
Thanks, can you give this a try? All I did was add some annotations and change the path, let me know if it works!
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: bytestash
  name: bytestash
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: my-domain.com
      http:
        paths:
          - backend:
              service:
                name: bytestash
                port:
                  number: 5000
            path: /bytestash(/|$)(.*)
            pathType: Prefix
```
