### ISSUE TITLE
[BUG] Cannot post a simple PHP code

### ISSUE THREAD

**Issue by windware-ono** [jordan-dalby/ByteStash#86]
**Describe the bug**
Posting a simple PHP code logs you out without being able to save it.
A red toast is shown saying, "Session expired. Please login again.".

**To Reproduce**
When posting a new snippet, type in anything (such as "A") for title and use the following as code `<?php print 1;`

**Expected behavior**
Code gets saved without being logged out.

**Platform**
Docker under Ubuntu 24.04.
ByteStash v1.4.1

**Comment by jordan-dalby** [comment]
@windware-ono 
Is this only with PHP?
What is your token expiry set to?

**Comment by windware-ono** [comment]
Not sure if this is PHP related but even with the type set as `plaintext` or not set, it still happens.
I've changed the expiry from `7d`, `7 days` and `365d` but nothing changed.
I can post if the snippet is only `<?php print 1` but as soon as it gets a semi colon at the end on save, I get logged out.

Is this not reproducible?

**Comment by jordan-dalby** [comment]
> Not sure if this is PHP related but even with the type set as `plaintext` or not set, it still happens. I've changed the expiry from `7d`, `7 days` and `365d` but nothing changed. I can post if the snippet is only `<?php print 1` but as soon as it gets a semi colon at the end on save, I get logged out.
> 
> Is this not reproducible?

No, I can't reproduce it. Just as a sanity check:
- Have you logged out & logged back in?
- Any errors in the ByteStash container?
- Browser?

**Comment by windware-ono** [comment]
- I can keep logging back in after I get logged out when posting the failed code.
  - I deleted the docker data dir and started as a clean slate but it still occurred.
- I see no logs from the docker container upon failed save after `Successfully fetched 3 snippets` when viewing the list.
- All the following browsers give the same error, so I guess browser isn't the culprit.
  - MacOS 15 : Chromium v130, Firefox v132, Safari 18
  - Windows 11 : Edge v131
- `token` does exist in local storage while editing but it's gone upon saving the failed code.

**Comment by windware-ono** [comment]
There was a browser console error upon saving the failed code.
<img width="1442" alt="Screenshot 2024-11-19 at 2 44 24" src="https://github.com/user-attachments/assets/6e8d24f8-31fd-4863-b746-ee9451d5922e">
Expanding the first error showed this.
<img width="1459" alt="Screenshot 2024-11-19 at 2 45 36" src="https://github.com/user-attachments/assets/c39eb723-e4b0-445a-832e-df4436dc357c">

**Comment by jordan-dalby** [comment]
@windware-ono 
F12 then open the network tab, click in the first "snippets", under Headers it should be marked as POST, what is under response? Perhaps 'Invalid token'?

Your docker compose should look something like this, make sure you aren't missing anything:
```
services:
  bytestash:
    image: "ghcr.io/jordan-dalby/bytestash:latest"
    container_name: bytestash
    volumes:
      - /path/to/data:/data/snippets
    ports:
      - 5000:5000
    environment:
      - AUTH_USERNAME=test
      - AUTH_PASSWORD=test
      - JWT_SECRET=YOUR_TOKEN_HERE
      - TOKEN_EXPIRY=24h
    restart: unless-stopped
```
